### ISSUE TITLE
Remove tokens

### ISSUE THREAD

**Issue by davestewart** [jeffbski/markdown-it-modify-token#4]
Hello!

I'm looking for something that might help me remove tags from a markdown, specifically H1s.

Could your plugin do this?

**Comment by jeffbski-rga** [comment]
My plugin is primarily for updating tokens, so I am not sure whether it can be used to completely remove them. However I would imagine that you could use https://github.com/martinheidegger/markdown-it-replace-link to replace H1's with empty string or a comment.

**Comment by davestewart** [comment]
Hey!

I got down and dirty in the end and figured out how to do it from scratch:

```js
function findIndex (state, tag, type) {
  return state.tokens.findIndex(token => {
    return token.tag === tag && token.type === type
  })
}

function plugin (state) {
  const start = findIndex(state, 'h1', 'heading_open')
  if (start > -1) {
    const end = findIndex(state, 'h1', 'heading_close')
    state.tokens.splice(start, (end - start) + 1 )
  }
}

module.exports = function (md) {
  md.core.ruler.push('strip_h1', plugin)
}
```

Thanks for the reply and the tip anyway!
